// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE6rt9BDqophYe6j-_HyIOvdt4ldNxgKM',
    appId: '1:443995392320:web:783aefc06a14e513bd12a5',
    messagingSenderId: '443995392320',
    projectId: 'bykakrentalcenter',
    authDomain: 'bykakrentalcenter.firebaseapp.com',
    storageBucket: 'bykakrentalcenter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgD1Zy46y1emnFfJfu6iS6i2Njrl9-Bpw',
    appId: '1:443995392320:android:7a06ef2e0c4d5bf6bd12a5',
    messagingSenderId: '443995392320',
    projectId: 'bykakrentalcenter',
    storageBucket: 'bykakrentalcenter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKO8xE4SaaVNh0pKthaNnUSDJEXpeDvWw',
    appId: '1:443995392320:ios:c517221baf704941bd12a5',
    messagingSenderId: '443995392320',
    projectId: 'bykakrentalcenter',
    storageBucket: 'bykakrentalcenter.appspot.com',
    iosClientId: '443995392320-i233cqj1g3bgb89dbsq3623j3ajib7c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bykaksuitrentalcenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKO8xE4SaaVNh0pKthaNnUSDJEXpeDvWw',
    appId: '1:443995392320:ios:c517221baf704941bd12a5',
    messagingSenderId: '443995392320',
    projectId: 'bykakrentalcenter',
    storageBucket: 'bykakrentalcenter.appspot.com',
    iosClientId: '443995392320-i233cqj1g3bgb89dbsq3623j3ajib7c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bykaksuitrentalcenter',
  );
}
